{
 "title": "Linkedin Oncall",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Probe Overview",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "probe_success{}" },
    { "expr": "probe_http_ssl{} > 0" },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{} - time()) / 3600 / 24"
    },
    { "expr": "probe_http_status_code{} > 0" },
    {
     "expr": "avg_over_time(probe_duration_seconds{}[1m])"
    },
    { "expr": "probe_tls_version_info{}" },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{}[1m])"
    }
   ]
  },
  {
   "title": "Oncall RED - Rate, Errors, Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Количество ошибок",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(rate(http_total_request_total{status=\"5..\"}[5m]))",
       "legendFormat": "response errors count"
      }
     ]
    },
    {
     "title": "Процент успешно обработанных запросов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 6 },
     "targets": [
      {
       "expr": "sum(rate(http_total_request_total{status=~\"201 Created|200 OK\"}[5m])) / sum(rate(http_total_request_total[5m])) * 100",
       "legendFormat": "Successfully processed requests in %"
      }
     ]
    },
    {
     "title": "Количество обработанных запросов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum(rate(http_total_request_total[5m]))",
       "legendFormat": "request processed count"
      }
     ]
    },
    {
     "title": "Задержка запросов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 14 },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(request_latency_seconds_bucket[5m])))",
       "legendFormat": "latency in seconds"
      }
     ]
    }
   ]
  },
  {
   "title": "Business metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Количество дежурных в различных командах",
     "type": "bargauge",
     "description": "Показывает количество главных дежурных и запасных дежурных в разрезе времени в каждой команде",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "duty", "legendFormat": "Team: {{team}} Role: {{role}}" }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Oncall Latest Logs",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "10" }, "type": "logs" }
       ],
       "query": "docker.container.labels.com_docker_compose_service: \"oncall-web\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Oncall Logs Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "bucketAggs": [
        {
         "id": "3",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "docker.container.labels.com_docker_compose_service: \"oncall-web\" and status : \"500\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "SLA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "SLA",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "mysql",
       "rawSql": "with api_twt as (\n  SELECT sum(value) as api_twt from sla_db.indicators\n  where name = 'prober_get_team_by_name_success_total'\n  and observed_at < now() and observed_at >= now() - interval 1 day\n),\napi_tdt as (\n  select sum(value) as api_tdt from sla_db.indicators\n  WHERE name = 'prober_get_team_by_name_fail_total'\n  and observed_at < now() and observed_at >= now() - interval 1 day\n),\ndb_twt as (\n  SELECT sum(value) as db_twt from sla_db.indicators\n  where name = 'prober_mysql_connection_success_total'\n  and observed_at < now() and observed_at >= now() - interval 1 day\n),\ndb_tdt as (\n  select sum(value) as db_tdt from sla_db.indicators\n  WHERE name = 'prober_mysql_connection_fail_total'\n  and observed_at < now() and observed_at >= now() - interval 1 day\n),\npage_twt as (\n  SELECT sum(value) as page_twt from sla_db.indicators\n  where name = 'prober_web_page_availability_success_total'\n  and observed_at < now() and observed_at >= now() - interval 1 day\n),\npage_tdt as (\n  select sum(value) as page_tdt from sla_db.indicators\n  WHERE name = 'prober_web_page_availability_fail_total'\n  and observed_at < now() and observed_at >= now() - interval 1 day\n)\nselect \n    (api_twt - api_tdt)/api_twt * 100,\n    (db_twt - db_tdt)/db_twt * 100,\n    (page_twt - page_tdt)/page_twt * 100\nfrom sla_db.indicators,\napi_twt, api_tdt, db_twt, db_tdt, page_twt, page_tdt"
      }
     ]
    }
   ]
  },
  {
   "title": "SLI's",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get team by name success (API)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "targets": [
      {
       "dataset": "mysql",
       "rawSql": "SELECT value, is_bad * slo as error, slo, observed_at as datetime from sla_db.indicators\nwhere name = 'prober_get_team_by_name_success_total'\nORDER BY observed_at"
      }
     ]
    },
    {
     "title": "Get team by name fail (API)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "targets": [
      {
       "dataset": "mysql",
       "rawSql": "SELECT value, is_bad as error, slo, observed_at as datetime from sla_db.indicators\nwhere name = 'prober_get_team_by_name_fail_total'"
      }
     ]
    },
    {
     "title": "Get team by name duration (API)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "targets": [
      {
       "dataset": "mysql",
       "rawSql": "SELECT value, is_bad as error, slo, observed_at as datetime from sla_db.indicators\nwhere name = 'prober_get_team_by_name_duration_seconds'"
      }
     ]
    },
    {
     "title": "MySQL connection success (DB)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "targets": [
      {
       "dataset": "mysql",
       "rawSql": "SELECT value, is_bad * slo as error, slo, observed_at as datetime from sla_db.indicators\nwhere name = 'prober_mysql_connection_success_total'"
      }
     ]
    },
    {
     "title": "MySQL connection fail (DB)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "targets": [
      {
       "dataset": "mysql",
       "rawSql": "SELECT value, is_bad as error, slo, observed_at as datetime from sla_db.indicators\nwhere name = 'prober_mysql_connection_fail_total'"
      }
     ]
    },
    {
     "title": "MySQL connection duration (API)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "targets": [
      {
       "dataset": "mysql",
       "rawSql": "SELECT value, is_bad as error, slo, observed_at as datetime from sla_db.indicators\nwhere name = 'prober_mysql_connection_duration_seconds'"
      }
     ]
    },
    {
     "title": "Main page request success (DB)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "targets": [
      {
       "dataset": "mysql",
       "rawSql": "SELECT value, is_bad * slo as error, slo, observed_at as datetime from sla_db.indicators\nwhere name = 'prober_web_page_availability_success_total'"
      }
     ]
    },
    {
     "title": "Main page request fail (DB)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "targets": [
      {
       "dataset": "mysql",
       "rawSql": "SELECT value, is_bad * slo as error, slo, observed_at as datetime from sla_db.indicators\nwhere name = 'prober_web_page_availability_fail_total'"
      }
     ]
    },
    {
     "title": "Main page request fail (DB)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "targets": [
      {
       "dataset": "mysql",
       "rawSql": "SELECT value, is_bad * 5 as error, slo, observed_at as datetime from sla_db.indicators\nwhere name = 'prober_web_page_availability_duration_seconds'"
      }
     ]
    }
   ]
  }
 ]
}