{
 "title": "System summary",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({instance=\"$instance\"},$instance)"
    }
   },
   { "name": "job", "label": "job", "query": { "query": "label_values($job,$job)" } }
  ]
 },
 "panels": [
  {
   "title": "System USE — Utilization, Saturation, Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "RAM",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "Utilization"
    },
    {
     "expr": "rate(node_vmstat_pgmajfault{instance=\"$instance\"}[5m])",
     "legendFormat": "Saturation"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total[5m])) * 100)",
     "legendFormat": "Utilization"
    },
    {
     "expr": "node_load1{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "Saturation"
    }
   ]
  },
  {
   "title": "Network Recieved",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"eth0\"}[5m])",
     "legendFormat": "Utilization"
    },
    {
     "expr": "irate(node_network_receive_drop_total{device=\"eth0\", instance=~\"$instance\", job=~\"$job\"}[5m])",
     "legendFormat": "Saturation"
    },
    {
     "expr": "irate(node_network_receive_errs_total{device=\"eth0\", instance=~\"$instance\", job=~\"$job\"}[5m])",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"eth0\"}[5m])",
     "legendFormat": "Utilization"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{device=\"eth0\", instance=~\"$instance\", job=~\"$job\"}[5m])",
     "legendFormat": "Saturation"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{device=\"eth0\", instance=~\"$instance\", job=~\"$job\"}[5m])",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"nvme0n1\"}[5m])",
     "legendFormat": "Utilization"
    },
    {
     "expr": "irate(node_disk_io_now{device=\"nvme0n1\", instance=~\"$instance\", job=~\"$job\"}[5m])",
     "legendFormat": "Saturation"
    },
    {
     "expr": "irate(node_filesystem_device_error{device=\"/dev/nvme0n1p1\", instance=~\"$instance\", job=~\"$job\"}[5m])",
     "legendFormat": "Errors"
    }
   ]
  },
  { "title": "Drill down", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$instance\", job=~\"$job\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\", job=~\"$job\"}) / node_memory_MemTotal_bytes{instance=~\"$instance\", job=~\"$job\"} * 100",
     "legendFormat": "Utilization"
    },
    {
     "expr": "rate(node_vmstat_pgmajfault[5m])",
     "legendFormat": "Saturation"
    }
   ]
  },
  {
   "title": "Network Recieved",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"eth0\"}[5m])",
     "legendFormat": "Utilization"
    },
    {
     "expr": "irate(node_network_receive_drop_total{device=\"eth0\"}[5m])",
     "legendFormat": "Saturation"
    },
    {
     "expr": "irate(node_network_receive_errs_total{device=\"eth0\"}[5m])",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Utilization"
    },
    { "expr": "node_load1", "legendFormat": "Saturation" }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"eth0\"}[5m])",
     "legendFormat": "Utilization"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{device=\"eth0\"}[5m])",
     "legendFormat": "Saturation"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{device=\"eth0\"}[5m])",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"nvme0n1\"}[5m])",
     "legendFormat": "Utilization"
    },
    {
     "expr": "irate(node_disk_io_now{device=\"nvme0n1\"}[5m])",
     "legendFormat": "Saturation"
    },
    {
     "expr": "irate(node_filesystem_device_error{device=\"/dev/nvme0n1p1\"}[5m])",
     "legendFormat": "Errors"
    }
   ]
  }
 ]
}