global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'oncall'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['oncall:8080']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8084']
